name: Package macOS application

on: push

jobs:
  package-macos:
    name: Package macOS application
    runs-on: macos-latest

    steps:
      - name: Install to homebrew
        run: |
          brew install homebank

      - name: dump some information
        run: |
          brew ls -v homebank
          brew --prefix homebank
          ls $(brew --prefix homebank)
          otool -L $(brew --prefix homebank)/bin/homebank

      - name: Checkout scripts
        uses: actions/checkout@v2
        with:
          path: packaging

      - name: Package
        run: |
          ./packaging/scripts/create-package homebank HomeBank.app
          zip -r Homebank Homebank.app
         
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: Homebank
          path: Homebank.zip
