name: Package macOS application

on: push

jobs:
  package-macos:
    name: Package macOS application
    runs-on: macos-latest

    steps:
      - name: Install to homebrew
        run: |
          brew install homebank

      - name: dump some information
        run: |
          brew ls -v homebank
          brew --prefix homebank
          ls $(brew --prefix homebank)
          otool -L $(brew --prefix homebank)/bin/homebank
        
      - name: Get and compile gtk-mac-bundler
        run: |
          git clone https://gitlab.gnome.org/GNOME/gtk-mac-bundler
          export DEVROOT=$(pwd)/devroot
          export XDG_CONFIG_HOME=$DEVROOT/config
          export PIP_CONFIG_DIR=$XDG_CONFIG_HOME/pip
          make -C gtk-mac-bundler install

      - name: Checkout scripts
        uses: actions/checkout@v2
        with:
          path: packaging

      - name: Package
        run: |
          ./packaging/scripts/create-package homebank HomeBank.app
          zip -r Homebank Homebank.app
         
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: Homebank
          path: Homebank.zip
